name: Build Creusot Docker image

on:
  push:
    branches: 'main'
    paths: ['sources/creusot/**', '.github/workflows/docker-creusot.yml']

jobs:
  docker:
    strategy:
        matrix:
          arch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: jonasalaif
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build ${{ matrix.arch }} Creusot image
        run: docker buildx build --platform linux/${{ matrix.arch }} --load -t jonasalaif/creusot:${{ matrix.arch }} ./sources/creusot

      - name: Run evaluation
        run: |
          cd sources
          docker run --rm --network none -v ${PWD}/russol-alpha/ruslic/tests/all:/all jonasalaif/creusot:${{ matrix.arch }} ./mlcfg /all/creusot.rs
      #     docker run --rm --network none -v ${PWD}/russol-alpha/ruslic/tests/all:/all jonasalaif/creusot:${{ matrix.arch }} ./prove /all/creusot.mlcfg

      - name: Save ${{ matrix.arch }} Creusot image
        run: |
          docker push jonasalaif/creusot:${{ matrix.arch }}
          docker tag jonasalaif/creusot:${{ matrix.arch }} jonasalaif/creusot:latest
          docker save jonasalaif/creusot:latest | gzip > creusot-${{ matrix.arch }}.tar.gz
      - name: Upload artifact creusot-${{ matrix.arch }}
        uses: actions/upload-artifact@v3
        with:
          name: creusot-${{ matrix.arch }}.tar.gz
          path: creusot-${{ matrix.arch }}.tar.gz
          retention-days: 1
      - name: Clean up after ${{ matrix.arch }} Creusot image
        run: |
          rm creusot-${{ matrix.arch }}.tar.gz
          docker rmi jonasalaif/creusot

  upload-latest:
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: jonasalaif
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Creusot image
        run: |
          docker manifest create jonasalaif/creusot:latest jonasalaif/creusot:amd64 jonasalaif/creusot:arm64
          docker manifest push jonasalaif/creusot:latest
