name: Build Russol Docker image

on:
  push:
    branches: 'main'
    paths: ['sources/russol-alpha', 'sources/demo/**', '.github/workflows/docker-russol.yml']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: jonasalaif
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build amd64 Russol image
        uses: docker/build-push-action@v4
        with:
          context: ./sources
          platforms: linux/amd64
          load: true
          tags: jonasalaif/russol:amd64

      - name: Run evaluation intro
        run: |
          cd sources
          docker run --rm --network none -v ${PWD}/demo.rs:/demo.rs jonasalaif/russol:amd64 run --release --bin ruslic /demo.rs
          docker run --rm --network none -v ${PWD}/demo:/demo jonasalaif/russol:amd64 run --release --bin cargo-russol -- --manifest-path=/demo/Cargo.toml
          docker run --rm --network none -v ${PWD}/russol-alpha/ruslic/tests/synth/paper/rust/stackoverflow/reborrow.rs:/reborrow.rs jonasalaif/russol:amd64 run --release --bin ruslic /reborrow.rs
          docker run --rm --network none -v ${PWD}/russol-alpha/ruslic/tests/synth/paper/rust/custom/list_ex/list_paper.rs:/list_paper.rs jonasalaif/russol:amd64 run --release --bin ruslic /list_paper.rs
      - name: Run evaluation benchmarks
        run: |
          cd sources
          docker run --rm --network none -v ${PWD}/russol-alpha/ruslic/tests/synth/paper:/home/sbtuser/russol-alpha/ruslic/tests/synth/paper jonasalaif/russol:amd64 test --release --test ci -- all_tests --nocapture
      # Skip due to very long runtime:
      # - name: Run evaluation top 100 crates
      #   run: |
      #     cd sources
      #     docker run --rm jonasalaif/russol:amd64 test --release --test top_crates -- top_crates_cached --nocapture

      - name: Build arm64 Russol image
        uses: docker/build-push-action@v4
        with:
          context: ./sources
          platforms: linux/arm64
          load: true
          tags: jonasalaif/russol:arm64

      - name: Push Russol image
        uses: docker/build-push-action@v4
        with:
          context: ./sources
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jonasalaif/russol:latest

      - name: Save Russol images
        run: |
          docker save jonasalaif/russol:amd64 | gzip > russol-amd64.tar.gz
          docker save jonasalaif/russol:arm64 | gzip > russol-arm64.tar.gz

      - name: Upload artifact russol-amd64
        uses: actions/upload-artifact@v3
        with:
          name: russol-amd64.tar.gz
          path: russol-amd64.tar.gz
          retention-days: 1

      - name: Upload artifact russol-arm64
        uses: actions/upload-artifact@v3
        with:
          name: russol-arm64.tar.gz
          path: russol-arm64.tar.gz
          retention-days: 1
