name: Build Russol Docker image

on:
  push:
    branches: 'main'
    paths: ['sources/russol-alpha', 'sources/demo/**', 'sources/Dockerfile', '.github/workflows/docker-russol.yml']

jobs:
  docker:
    strategy:
        matrix:
          arch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: jonasalaif
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build ${{ matrix.arch }} Russol image
        run: docker buildx build --platform linux/${{ matrix.arch }} --load -t jonasalaif/russol:${{ matrix.arch }} ./sources

      - name: Run evaluation intro
        run: |
          cd sources
          docker run --rm --network none -v ${PWD}/demo.rs:/demo.rs jonasalaif/russol:${{ matrix.arch }} run --release --bin ruslic /demo.rs
          docker run --rm --network none jonasalaif/russol:${{ matrix.arch }} run --release --bin cargo-russol -- --manifest-path=/home/sbtuser/demo/Cargo.toml
          docker run --rm --network none -v ${PWD}/russol-alpha/ruslic/tests/synth/paper/rust/b-stackoverflow/reborrow.rs:/reborrow.rs jonasalaif/russol:${{ matrix.arch }} run --release --bin ruslic /reborrow.rs
          docker run --rm --network none -v ${PWD}/russol-alpha/ruslic/tests/synth/paper/rust/c-custom/list_ex/list_paper.rs:/list_paper.rs jonasalaif/russol:${{ matrix.arch }} run --release --bin ruslic /list_paper.rs
      - name: Run evaluation benchmarks
        if: ${{ matrix.arch == 'amd64' }}
        run: |
          cd sources
          docker run --rm --network none jonasalaif/russol:${{ matrix.arch }} test --release --test ci -- all_tests --nocapture
      # Skip due to very long runtime:
      # - name: Run evaluation top 100 crates
      #   run: |
      #     cd sources
      #     docker run --rm jonasalaif/russol:${{ matrix.arch }} test --release --test top_crates -- top_crates_cached --nocapture

      - name: Save ${{ matrix.arch }} Russol image
        run: |
          docker push jonasalaif/russol:${{ matrix.arch }}
          docker tag jonasalaif/russol:${{ matrix.arch }} jonasalaif/russol:latest
          docker save jonasalaif/russol:latest | gzip > russol-${{ matrix.arch }}.tar.gz

      - name: Upload release russol-${{ matrix.arch }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: russol-${{ matrix.arch }}.tar.gz

      - name: Clean up after ${{ matrix.arch }} Russol image
        run: |
          rm russol-${{ matrix.arch }}.tar.gz
          docker rmi jonasalaif/russol

  upload-latest:
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: jonasalaif
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Russol image
        run: |
          docker manifest create jonasalaif/russol:latest jonasalaif/russol:amd64 jonasalaif/russol:arm64
          docker manifest push jonasalaif/russol:latest
