name: Build Creusot Docker image

on:
  push:
    branches: 'main'
    paths: ['sources/creusot/**', '.github/workflows/docker-creusot.yml']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: jonasalaif
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build amd64 Creusot image
        run: |
          docker build --platform linux/amd64 -t jonasalaif/creusot:amd64 ./sources/creusot
          docker push jonasalaif/creusot:amd64

      - name: Run evaluation
        run: |
          cd sources
          docker run --rm --network none -v ${PWD}/russol-alpha/ruslic/tests/all:/all jonasalaif/creusot:amd64 ./mlcfg /all/creusot.rs
      #     docker run --rm --network none -v ${PWD}/russol-alpha/ruslic/tests/all:/all jonasalaif/creusot:amd64 ./prove /all/creusot.mlcfg

      - name: Build arm64 Creusot image
        run: |
          docker build --platform linux/arm64 -t jonasalaif/creusot:arm64 ./sources/creusot
          docker push jonasalaif/creusot:arm64

      - name: Save Creusot images
        run: |
          docker tag jonasalaif/creusot:amd64 jonasalaif/creusot:latest
          docker save jonasalaif/creusot:latest | gzip > creusot-amd64.tar.gz
          docker tag jonasalaif/creusot:arm64 jonasalaif/creusot:latest
          docker save jonasalaif/creusot:latest | gzip > creusot-arm64.tar.gz

      - name: Upload artifact creusot-amd64
        uses: actions/upload-artifact@v3
        with:
          name: creusot-amd64.tar.gz
          path: creusot-amd64.tar.gz
          retention-days: 1

      - name: Upload artifact creusot-arm64
        uses: actions/upload-artifact@v3
        with:
          name: creusot-arm64.tar.gz
          path: creusot-arm64.tar.gz
          retention-days: 1

      - name: Push Creusot image
        run: |
          docker manifest create jonasalaif/creusot:latest --amend jonasalaif/creusot:amd64 --amend jonasalaif/creusot:arm64
          docker manifest push jonasalaif/creusot:latest
