name: Build Russol Docker image

on:
  push:
    branches: 'main'
    paths: ['russol-alpha', 'demo/**', '.github/workflows/docker-creusot.yml']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: jonasalaif
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Russol
        uses: docker/build-push-action@v4
        with:
          context: .
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: jonasalaif/russol:latest
