name: Build Creusot Docker image

on:
  push:
    branches: 'main'
    paths: ['creusot/**', '.github/workflows/docker-creusot.yml']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: jonasalaif
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Creusot image
        uses: docker/build-push-action@v4
        with:
          context: ./creusot
          load: true
          tags: jonasalaif/creusot:test

      # - name: Run evaluation
      #   run: |
      #     docker run --rm -v ${PWD}/russol-alpha/ruslic/tests/all:/all jonasalaif/creusot:test ./mlcfg /all/creusot.rs
      #     docker run --rm -v ${PWD}/russol-alpha/ruslic/tests/all:/all jonasalaif/creusot:test ./prove /all/creusot.mlcfg

      - name: Push Creusot image
        uses: docker/build-push-action@v4
        with:
          context: ./creusot
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jonasalaif/creusot:latest
