name: Create artifact

on:
  push:
    branches: 'main'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Create sources zip
        run: |
          cd sources
          chmod o+rw -R demo
          zip -r ../sources.zip creusot demo russol-alpha .dockerignore demo.rs Dockerfile STRUCTURE.md -x **/.git

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          retention-days: 7
          name: artifact.zip
          path: |
            sources.zip
            LICENSE
            README.md
