name: Create artifact

on:
  push:
    branches: 'main'
    paths: ['!.github/**', '.github/workflows/package-artifact.yml']

permissions:
  contents: write

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Create sources zip
        run: |
          cd sources
          chmod o+rw -R demo
          zip -r ../sources.zip creusot demo russol-alpha .dockerignore demo.rs Dockerfile STRUCTURE.md -x **/.git

      - name: Upload artifact files
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: |
            sources.zip
            LICENSE
            README.md
