name: Publish new version on Zenodo

on:
  workflow_dispatch:
    inputs:
      sandbox:
        description: 'Release to sandbox'
        type: boolean
        default: true
        required: false

env:
  DEPOSITION_ID: ${{ github.event.inputs.sandbox && '1181476' || '7794634' }}
  SERVER: ${{ github.event.inputs.sandbox && 'https://sandbox.zenodo.org' || 'https://zenodo.org' }}
  TOKEN: ${{ github.event.inputs.sandbox && secrets.ZENODO_SANDBOX_TOKEN || secrets.ZENODO_TOKEN }}

jobs:
  new_version:
    name: Create new version of zenodo deposition
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download release
        run: |
          gh release download latest -D release_files
          ls release_files/* > .zenodo_whitelist_uploads
        env:
            GH_TOKEN: ${{ github.token }}

      - uses: kykrueger/zenodo-new-version@v1.0.3
        with:
          zenodo_deposition_id: ${{ env.DEPOSITION_ID }}
          zenodo_server: ${{ env.SERVER }}
          zenodo_token: ${{ env.TOKEN }}
      - uses: kykrueger/zenodo-publish@v1.0.5
        with:
          zenodo_deposition_id: ${{ env.DEPOSITION_ID }}
          zenodo_server: ${{ env.SERVER }}
          zenodo_token: ${{ env.TOKEN }}
