name: Publish new version on Zenodo

on:
  workflow_dispatch:

env:
  zenodo_deposition_id: 1181476
  zenodo_server: 'https://sandbox.zenodo.org'

jobs:
  new_version:
    name: Create new version of zenodo deposition
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download release
        run: |
          gh release download latest -D release_files
          ls release_files/* > .zenodo_whitelist_uploads
        env:
            GH_TOKEN: ${{ github.token }}

      - uses: kykrueger/zenodo-new-version@v1.0.3
        with:
          zenodo_deposition_id: ${{ env.zenodo_deposition_id }}
          zenodo_server: ${{ env.zenodo_server }}
          zenodo_token: ${{ secrets.ZENODO_SANDBOX_TOKEN }}
      - uses: kykrueger/zenodo-publish@v1.0.5
        with:
          zenodo_deposition_id: ${{ env.zenodo_deposition_id }}
          zenodo_server: ${{ env.zenodo_server }}
          zenodo_token: ${{ secrets.ZENODO_SANDBOX_TOKEN }}
